package com.sipa.boot.java8.common.exceptions;

import java.util.Optional;

import com.sipa.boot.java8.common.constants.SipaBootCommonConstants;

/**
 * @author caszhou
 * @date 2021/9/28
 */
public class NotAcceptableException extends ApplicationException {
    public static final int DEFAULT_NOT_ACCEPTABLE_EXCEPTION_STATUS_CODE = SipaBootCommonConstants.Http.NOT_ACCEPTABLE;

    public static final int DEFAULT_NOT_ACCEPTABLE_EXCEPTION_NUMERIC_ERROR_CODE = 20002;

    public static final String DEFAULT_NOT_ACCEPTABLE_EXCEPTION_ERROR_CODE =
        "errors.com.sipa.boot.request_not_acceptable";

    public static final String DEFAULT_NOT_ACCEPTABLE_EXCEPTION_ERROR_MESSAGE =
        "Your request could not be processed as you do not accept the response type generated by this resource.";

    public NotAcceptableException() {
        this(DEFAULT_NOT_ACCEPTABLE_EXCEPTION_ERROR_MESSAGE);
    }

    public NotAcceptableException(String pattern, Object... args) {
        this(DEFAULT_NOT_ACCEPTABLE_EXCEPTION_NUMERIC_ERROR_CODE, DEFAULT_NOT_ACCEPTABLE_EXCEPTION_ERROR_CODE, pattern,
            args);
    }

    public NotAcceptableException(int numericErrCode, String errCode, String pattern, Object... args) {
        super(DEFAULT_NOT_ACCEPTABLE_EXCEPTION_STATUS_CODE, numericErrCode,
            Optional.ofNullable(errCode).orElse(DEFAULT_NOT_ACCEPTABLE_EXCEPTION_ERROR_CODE), pattern, args);
    }
}
